### ISSUE TITLE
Issues with Wolfman_123_

### ISSUE THREAD

**Issue by retep998** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#17]
`Wolfman_123_` is the original account which was renamed from `Wolfman-123-` during the Gamepedia transition due to Curse username limitations. Unfortunately this new username left Wolfman in a broken state unable to do anything so Curse tried to rename Wolfman but ended up creating a second conflicting account.

Several days ago it was:

```
Wolfman 123 (Talk | contribs | block) (autoreview, editor, reviewer, staff) (Created on 29 November 2014 at 15:11)
Wolfman 123  (Talk | contribs | block) (autoreview, editor, reviewer, staff) (Created on 9 October 2014 at 16:18)
```

As of today it is now:

```
Wolfman 123 (Talk | contribs | block) (Created on 6 January 2015 at 01:02)`
Wolfman 123  (Talk | contribs | block) (autoreview, editor, reviewer, staff) (Created on 9 October 2014 at 16:18)
```

Because MediaWiki treats `Wolfman_123` and `Wolfman_123_` as identical, it causes weird issues.
For example, pages which were edited by Wolfman on his old account were added to his watchlist so when someone tried to edit such a page, Mediawiki would attempt to send an e-mail notification to Wolfman, and then error because of two accounts with the same name and the edit would be reverted. During one such edit attempt I got a stacktrace.

```
Unexpected non-MediaWiki exception encountered, of type "Exception"
[4e749144] /index.php?title=Template:Cg/Inscriber&action=submit Exception from line 464 of /home/hydra/public_html/mouse/database/mysqli.php: [1062] Duplicate entry 'Wolfman 123' for key 'user_name'

Backtrace:
#0 /home/hydra/public_html/mouse/database/mysqli.php(419): mouseDatabaseMysqli->dbError()
#1 /home/hydra/public_html/mouse/database/mysqli.php(314): mouseDatabaseMysqli->query(string)
#2 /home/hydra/public_html/extensions/CurseAuth/classes/renameUser.php(131): mouseDatabaseMysqli->update(string, array, string)
#3 /home/hydra/public_html/extensions/CurseAuth/CurseAuthPlugin.php(361): renameUser->doRename()
#4 /home/hydra/public_html/extensions/CurseAuth/CurseAuth.hooks.php(542): CurseAuthPlugin->updateUser(User)
#5 [internal function]: CurseAuthHooks::onUserSaveSettings(User)
#6 /home/hydra/public_html/includes/Hooks.php(206): call_user_func_array(string, array)
#7 /home/hydra/public_html/includes/GlobalFunctions.php(4013): Hooks::run(string, array, NULL)
#8 /home/hydra/public_html/includes/User.php(3440): wfRunHooks(string, array)
#9 /home/hydra/public_html/extensions/CurseAuth/CurseAuth.hooks.php(731): User->saveSettings()
#10 [internal function]: CurseAuthHooks::onUserGetEmailAuthenticationTimestamp(User, string)
#11 /home/hydra/public_html/includes/Hooks.php(206): call_user_func_array(string, array)
#12 /home/hydra/public_html/includes/GlobalFunctions.php(4013): Hooks::run(string, array, NULL)
#13 /home/hydra/public_html/includes/User.php(2361): wfRunHooks(string, array)
#14 /home/hydra/public_html/includes/User.php(4053): User->getEmailAuthenticationTimestamp()
#15 /home/hydra/public_html/includes/UserMailer.php(648): User->isEmailConfirmed()
#16 /home/hydra/public_html/includes/UserMailer.php(581): EmailNotification->actuallyNotifyOnPageChange(User, Title, string, string, integer, integer, array, string)
#17 /home/hydra/public_html/includes/changes/RecentChange.php(291): EmailNotification->notifyOnPageChange(User, Title, string, string, integer, integer, string)
#18 /home/hydra/public_html/includes/changes/RecentChange.php(549): RecentChange->save()
#19 /home/hydra/public_html/includes/WikiPage.php(1857): RecentChange::notifyEdit(string, Title, boolean, User, string, integer, string, integer, string, integer, integer, integer, boolean)
#20 [internal function]: WikiPage->doEditContent(WikitextContent, string, integer, boolean, NULL, string)
#21 /home/hydra/public_html/includes/Article.php(2024): call_user_func_array(array, array)
#22 /home/hydra/public_html/includes/EditPage.php(1830): Article->__call(string, array)
#23 /home/hydra/public_html/includes/EditPage.php(1830): Article->doEditContent(WikitextContent, string, integer, boolean, NULL, string)
#24 /home/hydra/public_html/includes/EditPage.php(1243): EditPage->internalAttemptSave(array, boolean)
#25 /home/hydra/public_html/includes/EditPage.php(433): EditPage->attemptSave()
#26 /home/hydra/public_html/includes/actions/EditAction.php(50): EditPage->edit()
#27 /home/hydra/public_html/includes/actions/EditAction.php(74): EditAction->show()
#28 /home/hydra/public_html/includes/Wiki.php(428): SubmitAction->show()
#29 /home/hydra/public_html/includes/Wiki.php(292): MediaWiki->performAction(Article, Title)
#30 /home/hydra/public_html/includes/Wiki.php(588): MediaWiki->performRequest()
#31 /home/hydra/public_html/includes/Wiki.php(447): MediaWiki->main()
#32 /home/hydra/public_html/index.php(46): MediaWiki->run()
#33 {main}
```

When Wolfman logged in to his old account and removed those pages from his watchlist they would become easily editable again without timeouts or reverts.

**Comment by Wolfman-123-** [comment]
Correction:
On the original wiki my username was `Wolfman-123-`; which due to limitations of the Curse auth, was renamed to `Wolfman_123_`, which at the time was the name of my Curse account.

It wasn't made apparent until using the gamepedia wiki for a short period of time, where it was noticed that this username presented numerous problems due the inclusion of the trailing underscore which is automatically removed by url encoding within gamepedia sites.

After much confusion and numerous contacting with curse/gamepedia staff, my curse username was renamed to `Wolfman_123`. This change appeared to work well and all urls worked correctly, however it was then noticed that a duplicate account was still present on the ftb wiki. As retep explained 2 separate accounts to this point still exist, both of which I am access by simply changing the username field when logging in.

**Comment by Telshin** [comment]
Your account should be fixed after some DB fun times.
