### ISSUE TITLE
Sparadic Issue

### ISSUE THREAD

**Issue by Chocohead** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#29]
Just had this error when previewing an edit, haven't made it happen again but thought it might mean something important to someone.

```
Unexpected non-MediaWiki exception encountered, of type "RedisException"
[1ed0517e] /index.php?title=Scrap_Box&action=submit Exception from line 436 of /home/hydra/public_html/includes/clientpool/RedisConnectionPool.php: read error on connection
Backtrace:
#0 [internal function]: Redis->hGet(string, string)
#1 /home/hydra/public_html/includes/clientpool/RedisConnectionPool.php(436): call_user_func_array(array, array)
#2 /home/hydra/public_html/extensions/SEO/SEOHooks.php(293): RedisConnRef->__call(string, array)
#3 /home/hydra/public_html/extensions/SEO/SEOHooks.php(293): RedisConnRef->hGet(string, string)
#4 [internal function]: SEOHooks::onOutputPageBeforeHTML(OutputPage, string)
#5 /home/hydra/public_html/includes/Hooks.php(206): call_user_func_array(string, array)
#6 /home/hydra/public_html/includes/GlobalFunctions.php(4061): Hooks::run(string, array, NULL)
#7 /home/hydra/public_html/includes/EditPage.php(2847): wfRunHooks(string, array)
#8 /home/hydra/public_html/includes/EditPage.php(2819): EditPage->showPreview(string)
#9 /home/hydra/public_html/includes/EditPage.php(2254): EditPage->displayPreviewArea(string, boolean)
#10 /home/hydra/public_html/includes/EditPage.php(458): EditPage->showEditForm()
#11 /home/hydra/public_html/includes/actions/EditAction.php(50): EditPage->edit()
#12 /home/hydra/public_html/includes/actions/EditAction.php(74): EditAction->show()
#13 /home/hydra/public_html/includes/Wiki.php(428): SubmitAction->show()
#14 /home/hydra/public_html/includes/Wiki.php(292): MediaWiki->performAction(Article, Title)
#15 /home/hydra/public_html/includes/Wiki.php(588): MediaWiki->performRequest()
#16 /home/hydra/public_html/includes/Wiki.php(447): MediaWiki->main()
#17 /home/hydra/public_html/index.php(46): MediaWiki->run()
#18 {main}
```

**Comment by Chocohead** [comment]
Had it a few more times tonight viewing and saving pages, as well as the wiki being really slow at times.

**Comment by elifoster** [comment]
The wiki has definitely been loading slowly lately.
