### ISSUE TITLE
Login exception

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#8]
Please see http://puu.sh/dHqKP/e05ed1b11d.png for a backtrace.

**Comment by Telshin** [comment]
Are you still getting this exception?

**Comment by elifoster** [comment]
Yeah, but in case it's a different one this time:

```
Unexpected non-MediaWiki exception encountered, of type "Exception"
[f6afd654] /index.php?title=Special:UserLogin&action=submitlogin&type=login Exception from line 464 of /home/hydra/public_html/mouse/database/mysqli.php: [1062] Duplicate entry 'TheSatanicSanta' for key 'user_name'

Backtrace:
#0 /home/hydra/public_html/mouse/database/mysqli.php(419): mouseDatabaseMysqli->dbError()
#1 /home/hydra/public_html/mouse/database/mysqli.php(314): mouseDatabaseMysqli->query(string)
#2 /home/hydra/public_html/extensions/CurseAuth/classes/renameUser.php(131): mouseDatabaseMysqli->update(string, array, string)
#3 /home/hydra/public_html/extensions/CurseAuth/CurseAuthPlugin.php(361): renameUser->doRename()
#4 /home/hydra/public_html/includes/specials/SpecialUserlogin.php(741): CurseAuthPlugin->updateUser(User)
#5 /home/hydra/public_html/includes/specials/SpecialUserlogin.php(866): LoginForm->authenticateUserData()
#6 /home/hydra/public_html/includes/specials/SpecialUserlogin.php(227): LoginForm->processLogin()
#7 /home/hydra/public_html/includes/specialpage/SpecialPage.php(379): LoginForm->execute(NULL)
#8 /home/hydra/public_html/includes/specialpage/SpecialPageFactory.php(506): SpecialPage->run(NULL)
#9 /home/hydra/public_html/includes/Wiki.php(285): SpecialPageFactory::executePath(Title, RequestContext)
#10 /home/hydra/public_html/includes/Wiki.php(588): MediaWiki->performRequest()
#11 /home/hydra/public_html/includes/Wiki.php(447): MediaWiki->main()
#12 /home/hydra/public_html/index.php(46): MediaWiki->run()
#13 {main}
```

**Comment by Telshin** [comment]
Mind trying one more time?
